env: "MiniGrid-GoToDoorAddress-v0"
eval_env: "MiniGrid-GoToDoorAddressExtrapolate-v0"
model: "GoToDoorAddressNumericNACPostNonlinearity"
text: False
number: True
use_nac: True

seed:
  sample: cartesian
  from:
    - 0
    - 1
    - 2
    - 3
    - 4

