env: "MiniGrid-GoToDoorAddressText-v0"
eval_env: "MiniGrid-GoToDoorAddressExtrapolate-v0"
model: "GoToDoorAddressText"
text: True
number: False
use_nac: False

seed:
  sample: cartesian
  from:
    - 0
    - 1
    - 2
    - 3
    - 4

