procs: 8
cpus: 4
env_name: navi-generalization
mem: 8
n_search: -1 # -1 figures out the size of cartesian product for you
time: "'3:59:00'"
base_dir: /home/mila/w/weissmar/navi-generalization/rl-starter-files/outputs/
frames: 1000000
code_loc: /home/mila/w/weissmar/navi-generalization/rl-starter-files
#use_tmpdir: false
#weights_dir: $SCRATCH/weights
